version: "3"

services:
  dispatching:
    build:
      context: ./
      dockerfile: ./dispatching/src/main/docker/dockerfile
    restart: on-failure
    environment:
      - DISCOVERY_START=1
      - DISCOVERY_END=3
    depends_on:
      - plane-1
      - plane-2
      - plane-3
    links:
      - plane-1
      - plane-2
      - plane-3
    ports:
      - "8080:8080"

  plane-1:
    build:
      context: ./
      dockerfile: ./plane/src/main/docker/dockerfile
    image: plane
    restart: on-failure
    environment:
      - PLANE_ID=1
      - PLANE_TYPE=AIRLINER
      - PLANE_NAME="Boeing 747"
      - PLANE_CAPACITY=524
      - PLANE_START="Paris"
      - PLANE_DESTINATION="London"

  plane-2:
    image: plane
    restart: on-failure
    environment:
      - PLANE_ID=2
      - PLANE_TYPE=AIRLINER
      - PLANE_NAME="Airbus A320"
      - PLANE_CAPACITY=200
      - PLANE_START="Prague"
      - PLANE_DESTINATION="Barcelona"

  plane-3:
    image: plane
    restart: on-failure
    environment:
      - PLANE_ID=3
      - PLANE_TYPE=PRIVATE_PLANE
      - PLANE_NAME="Eclipse 500"
      - PLANE_CAPACITY=4
      - PLANE_START="Dubai"
      - PLANE_DESTINATION="Abu Dhabi"