FROM gradle:7.4.2-jdk11 as builder
USER root
RUN mkdir /dispatching
WORKDIR /dispatching
COPY . .
RUN gradle :dispatching:clean :dispatching:shadowJar
RUN mv dispatching/build/libs/dispatching-all.jar dispatching.jar

FROM openjdk:11-jre-slim
USER root
WORKDIR /dispatching
COPY --from=builder ./dispatching/dispatching.jar dispatching.jar
CMD ["java", "-jar", "dispatching.jar"]
